include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    dead_code: ignore
    unused_import: warning
    unused_local_variable: warning
    todo: info
    avoid_print: warning
    missing_return: error
    missing_required_param: error
   

  language:
    strict-casts: false
    strict-raw-types: true

linter:
  rules:
    # ---------------- Code Style ----------------
    prefer_single_quotes: true
    require_trailing_commas: true
    always_declare_return_types: true
    curly_braces_in_flow_control_structures: true


    # ---------------- Best Practices ----------------
    avoid_print: true
    avoid_redundant_argument_values: true
    avoid_unnecessary_containers: true
    avoid_returning_null_for_future: true
    avoid_void_async: true
    use_build_context_synchronously: true

    # ---------------- Performance ----------------
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    unnecessary_const: true

    # ---------------- Readability ----------------
    prefer_final_locals: true
    prefer_final_fields: true
    always_use_package_imports: false

    # ---------------- Safety ----------------
    avoid_dynamic_calls: true
    null_check_on_nullable_type_parameter: true
    cancel_subscriptions: true
    close_sinks: true
