include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    dead_code: ignore
    unused_import: warning
    unused_local_variable: warning
    todo: info

linter:
  rules:
    # Code Style
    prefer_single_quotes: true
    require_trailing_commas: true
    always_declare_return_types: true

    # Best Practices
    avoid_print: true
    avoid_redundant_argument_values: true
    avoid_unnecessary_containers: true
    avoid_returning_null_for_future: true

    # Performance
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true

    # Readability
    prefer_final_locals: true
    prefer_final_fields: true

    # Safety
    avoid_dynamic_calls: true
    null_check_on_nullable_type_parameter: true
